# Build and push a Docker image 

trigger:
- master

resources:
- repo: self

variables:
  tag: $(Build.BuildId)
  acr: syspython.azurecr.io

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: 'Dockerfile'
        tags: |
          $(tag)
    - task: Docker@2
      displayName: Push docker image to ACR
      inputs:
        containerRegistry: $(acr)
        command: push
