version: '3.4'

services:
  clamav-server:
    image: mkodockx/docker-clamav

  webapp:
    build: .
    depends_on:
      - clamav-server
    ports:
      - "5001:5000"  # Expose on host port 5001 to avoid Jenkins port 8080
    env_file:
      - local.env
