version: '3.4'

services:
  clamav-server:
    image: mkodockx/docker-clamav

  webapp:
    depends_on:
      - clamav-server
# replace below on deployment with image
    build: .
    ports:
      - 8081:8080
    env_file:
      - local.env
